FROM node:12.14-alpine3.10

RUN mkdir /src

ENV PATH="/node_modules/.bin:$PATH"
ENV REACT_APP_FP_ENV="development"

WORKDIR /src
ADD package.json /package.json
ENV NODE_PATH=/node_modules

RUN cd / && yarn install
