image: node:12.14

stages:
  - unittest
  - buildAndDeploy

run-unit-test-frontend:
  stage: unittest
  script:
    - cd frontend
    - yarn install
    - yarn test
  only:
    - merge_requests

run-unit-test-backend:
  stage: unittest
  script:
    - cd backend
    - yarn install
    - yarn test
  only:
    - merge_requests

build-and-deploy:
  stage: buildAndDeploy
  image: google/cloud-sdk:latest
  script:
    - ./release.sh
  only:
    - /^staging$/
