version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: formpress-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=formpress
      - MYSQL_USER=formpress
      - MYSQL_PASSWORD=formpress
    ports:
      - '3003:3306'
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.development
    container_name: formpress-backend
    command: 'yarn start-dev'
    working_dir: /src
    volumes:
      - ./backend:/src
      - ./frontend:/frontend
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_DATABASE=formpress
      - MYSQL_HOST=mysql
      - MYSQL_USER=formpress
      - MYSQL_PASSWORD=formpress
      - NODE_ENV=production
      - SERVER_PORT=3001
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - GOOGLE_SERVICE_ACCOUNT_CREDENTIALS=${GOOGLE_SERVICE_ACCOUNT_CREDENTIALS}
      - FILE_UPLOAD_BUCKET=${FILE_UPLOAD_BUCKET}
    ports:
      - '3001:3001'
    links:
      - 'mysql'
    depends_on:
      - 'mysql'
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.development
    container_name: formpress-frontend
    command: 'yarn start-compose'
    working_dir: /src
    volumes:
      - ./frontend:/src
    environment:
      - REACT_APP_BACKEND=http://localhost:3001
    ports:
      - '3000:3000'
    stdin_open: true
    links:
      - 'backend'
    depends_on:
      - 'backend'
