FROM node:12.14-alpine3.10

RUN apk add mailx postfix

RUN mkdir /src

ENV PATH="/node_modules/.bin:$PATH"
ENV FP_ENV=development
ENV FP_HOST=http://localhost

WORKDIR /src
ADD package.json /package.json
ENV NODE_PATH=/node_modules

EXPOSE 3001

RUN cd / && yarn install
